# -*- coding: utf-8 -*-
# Copyright 2020 - Today TechKhedut.
# Part of TechKhedut. See LICENSE file for full copyright and licensing details.
import logging

from odoo import api, fields, models, _
from odoo.exceptions import ValidationError

_logger = logging.getLogger(__name__)


class FreightStatement(models.Model):
    """Customer settlement statement generated from freight.service lines."""
    _name = 'freight.statement'
    _description = 'Customer Settlement Statement'
    _inherit = ['mail.thread', 'mail.activity.mixin']
    _rec_name = 'name'
    _order = 'id desc'

    FROZEN_HEADER_FIELDS = ('freight_operation_id', 'customer_id', 'settlement_date',
                            'company_id', 'currency_id')

    name = fields.Char(string='Statement Number', required=True, readonly=True,
                       copy=False, index=True, tracking=True)
    freight_operation_id = fields.Many2one('freight.shipment', string='Freight Operation',
                                           required=True, ondelete='cascade',
                                           index=True, tracking=True)
    customer_id = fields.Many2one('res.partner', string='Customer', required=True,
                                  tracking=True)
    company_id = fields.Many2one('res.company', related='freight_operation_id.company_id',
                                 string='Company', store=True, readonly=True)
    currency_id = fields.Many2one('res.currency', related='company_id.currency_id',
                                  string='Company Currency', store=True, readonly=True)
    state = fields.Selection([
        ('draft', 'Draft'),
        ('voided', 'Voided'),
        ('confirmed', 'Confirmed'),
        ('draft_invoice', 'Draft Invoice'),
    ], string='Status', default='draft', required=True, readonly=True,
       tracking=True, copy=False)
    version_no = fields.Integer(string='Version', default=1, required=True,
                                readonly=True, copy=False)
    statement_id = fields.Many2one('freight.statement', string='Root Statement',
                                   readonly=True, copy=False, index=True)
    previous_statement_id = fields.Many2one('freight.statement', string='Previous Statement',
                                            readonly=True, copy=False, index=True)
    statement_line_ids = fields.One2many('freight.statement.line', 'statement_id',
                                         string='Statement Lines', copy=False)
    settlement_date = fields.Date(string='Settlement Date',
                                  default=fields.Date.context_today,
                                  required=True, tracking=True, copy=False)
    currency_summary = fields.Text(string='Currency Summary', compute='_compute_currency_summary')
    amount_untaxed = fields.Monetary(string='Untaxed Amount', currency_field='currency_id',
                                     compute='_compute_amounts', store=True)
    tax_amount = fields.Monetary(string='Tax Amount', currency_field='currency_id',
                                 compute='_compute_amounts', store=True)
    amount_total = fields.Monetary(string='Total Amount', currency_field='currency_id',
                                   compute='_compute_amounts', store=True)
    invoice_ids = fields.Many2many('account.move', string='Draft Invoices',
                                   readonly=True, copy=False)
    invoice_count = fields.Integer(string='Invoice Count', compute='_compute_invoice_count')
    confirmed_uid = fields.Many2one('res.users', string='Confirmed By',
                                    readonly=True, copy=False)
    confirmed_date = fields.Datetime(string='Confirmed On', readonly=True, copy=False)
    voided_uid = fields.Many2one('res.users', string='Voided By',
                                 readonly=True, copy=False)
    voided_date = fields.Datetime(string='Voided On', readonly=True, copy=False)
    draft_invoice_uid = fields.Many2one('res.users', string='Draft Invoice Generated By',
                                        readonly=True, copy=False)
    draft_invoice_date = fields.Datetime(string='Draft Invoice Generated On',
                                         readonly=True, copy=False)

    @api.depends('statement_line_ids.amount_untaxed_company',
                 'statement_line_ids.tax_amount_company',
                 'statement_line_ids.amount_total_company')
    def _compute_amounts(self):
        for rec in self:
            lines = rec.statement_line_ids
            rec.amount_untaxed = sum(lines.mapped('amount_untaxed_company'))
            rec.tax_amount = sum(lines.mapped('tax_amount_company'))
            rec.amount_total = sum(lines.mapped('amount_total_company'))

    @api.depends('statement_line_ids.amount_untaxed',
                 'statement_line_ids.tax_amount',
                 'statement_line_ids.amount_total_company')
    def _compute_currency_summary(self):
        for rec in self:
            summary_lines = []
            for currency in rec.statement_line_ids.mapped('currency_id'):
                currency_lines = rec.statement_line_ids.filtered(
                    lambda line: line.currency_id == currency)
                untaxed = sum(currency_lines.mapped('amount_untaxed'))
                tax = sum(currency_lines.mapped('tax_amount'))
                company_total = sum(currency_lines.mapped('amount_total_company'))
                summary_lines.append(
                    '%s: untaxed %s / tax %s / total %s (company %s)' % (
                        currency.name, untaxed, tax, untaxed + tax, company_total))
            rec.currency_summary = '\n'.join(summary_lines) or _('No lines')

    @api.depends('invoice_ids')
    def _compute_invoice_count(self):
        for rec in self:
            rec.invoice_count = len(rec.invoice_ids)

    @api.model
    def _ensure_statement_sequence(self, company):
        """Return the company statement sequence, creating it once when missing."""
        sequence = self.env['ir.sequence'].sudo().search([
            ('code', '=', 'freight.statement'),
            '|', ('company_id', '=', False), ('company_id', '=', company.id),
        ], limit=1)
        if not sequence:
            sequence = self.env['ir.sequence'].sudo().create({
                'name': 'Freight Statement',
                'code': 'freight.statement',
                'prefix': 'STM/%(year)s%(month)s/',
                'padding': 4,
                'number_increment': 1,
                'number_next': 1,
                'company_id': company.id,
            })
        return sequence

    @api.model
    def _next_statement_name(self, company):
        sequence = self._ensure_statement_sequence(company)
        return sequence.with_company(company.id).next_by_id()

    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            operation = self.env['freight.shipment'].browse(vals.get('freight_operation_id'))
            company = operation.company_id or self.env.company
            if not vals.get('name'):
                vals['name'] = self._next_statement_name(company)
            previous = self.search([
                ('freight_operation_id', '=', vals.get('freight_operation_id')),
                ('customer_id', '=', vals.get('customer_id')),
            ], order='version_no desc, id desc', limit=1)
            if previous:
                vals['version_no'] = previous.version_no + 1
                vals['statement_id'] = previous.statement_id.id or previous.id
                vals['previous_statement_id'] = previous.id
            else:
                vals['version_no'] = 1
        statements = super().create(vals_list)
        for statement in statements:
            if not statement.statement_id:
                statement.write({'statement_id': statement.id})
            active = self.search([
                ('freight_operation_id', '=', statement.freight_operation_id.id),
                ('customer_id', '=', statement.customer_id.id),
                ('state', 'in', ('draft', 'confirmed', 'draft_invoice')),
                ('id', '!=', statement.id),
            ])
            if active:
                raise ValidationError(_(
                    'A non-voided settlement statement already exists for this freight '
                    'operation and customer. Void the current statement before generating '
                    'a new version.'))
        return statements

    def write(self, vals):
        for rec in self:
            if set(vals) & set(self.FROZEN_HEADER_FIELDS) and \
                    rec.state in ('voided', 'confirmed', 'draft_invoice'):
                raise ValidationError(_(
                    'Voided, confirmed and draft-invoice statements are immutable. '
                    'Changes must go back to freight.service and be regenerated as a '
                    'new statement version.'))
            if 'statement_id' in vals:
                if rec.statement_id or vals.get('statement_id') != rec.id:
                    raise ValidationError(_(
                        'The root statement reference cannot be changed.'))
        return super().write(vals)

    def unlink(self):
        if self.filtered(lambda rec: rec.state != 'draft'):
            raise ValidationError(_(
                'Only draft statements can be deleted. Void the statement instead.'))
        return super().unlink()

    def action_void(self):
        """Customer rejected the statement: void it and release the fees."""
        for rec in self:
            if rec.state != 'draft':
                raise ValidationError(_('Only draft statements can be voided.'))
            rec.write({
                'state': 'voided',
                'voided_uid': self.env.uid,
                'voided_date': fields.Datetime.now(),
            })
        return True

    def action_confirm(self):
        """Customer accepted the statement: freeze the snapshot."""
        for rec in self:
            if rec.state != 'draft':
                raise ValidationError(_('Only draft statements can be confirmed.'))
            if not rec.statement_line_ids:
                raise ValidationError(_('Cannot confirm a statement without lines.'))
            rec.write({
                'state': 'confirmed',
                'confirmed_uid': self.env.uid,
                'confirmed_date': fields.Datetime.now(),
            })
        return True

    def _find_sale_tax(self, rate):
        if not rate:
            return self.env['account.tax']
        return self.env['account.tax'].sudo().search([
            ('type_tax_use', '=', 'sale'),
            ('amount', '=', rate),
            ('company_id', '=', self.company_id.id),
        ], limit=1)

    def _prepare_invoice_line(self, line):
        """Draft invoice line preserving the statement tax-adjusted total."""
        base_price = line.amount_untaxed / line.qty if line.qty else line.price_unit
        computed_tax = round(line.amount_untaxed * line.tax_rate / 100.0, 2)
        tax = self._find_sale_tax(line.tax_rate)
        if tax and round(line.tax_amount, 2) == computed_tax:
            return {
                'product_id': line.product_id.id,
                'name': line.name,
                'quantity': line.qty,
                'price_unit': base_price,
                'tax_ids': [(6, 0, tax.ids)],
            }
        price_unit = line.amount_total / line.qty if line.qty else line.amount_total
        return {
            'product_id': line.product_id.id,
            'name': line.name,
            'quantity': line.qty,
            'price_unit': price_unit,
        }

    def action_generate_draft_invoice(self):
        """Generate one draft out_invoice per original currency (B-24 / B-38)."""
        self.ensure_one()
        if self.state == 'draft_invoice':
            return self._invoice_action(self.invoice_ids)
        if self.state != 'confirmed':
            raise ValidationError(_(
                'Only confirmed statements can generate draft customer invoices.'))
        grouped_lines = {}
        for line in self.statement_line_ids:
            grouped_lines.setdefault(line.currency_id.id, self.env['freight.statement.line'])
            grouped_lines[line.currency_id.id] |= line
        invoices = self.env['account.move']
        for currency_id, lines in grouped_lines.items():
            currency = self.env['res.currency'].browse(currency_id)
            existing = self.invoice_ids.filtered(
                lambda inv: inv.currency_id.id == currency_id)
            if existing:
                invoices |= existing
                continue
            invoices |= self.env['account.move'].create({
                'move_type': 'out_invoice',
                'partner_id': self.customer_id.id,
                'currency_id': currency.id,
                'invoice_date': fields.Date.context_today(self),
                'freight_operation_id': self.freight_operation_id.id,
                'freight_statement_id': self.id,
                'invoice_line_ids': [
                    (0, 0, self._prepare_invoice_line(line)) for line in lines
                ],
            })
        if invoices:
            self.write({
                'state': 'draft_invoice',
                'draft_invoice_uid': self.env.uid,
                'draft_invoice_date': fields.Datetime.now(),
                'invoice_ids': [(4, invoice.id, 0) for invoice in invoices],
            })
        return self._invoice_action(invoices)

    def _invoice_action(self, invoices):
        action = self.env['ir.actions.act_window']._for_xml_id(
            'account.action_move_out_invoice_type')
        action['domain'] = [('id', 'in', invoices.ids)]
        action['context'] = {'create': False}
        return action

    def button_open_invoices(self):
        self.ensure_one()
        return self._invoice_action(self.invoice_ids)


class FreightStatementLine(models.Model):
    """Immutable snapshot of a freight.service line inside a statement."""
    _name = 'freight.statement.line'
    _description = 'Customer Settlement Statement Line'
    _rec_name = 'name'
    _order = 'sequence, id'

    statement_id = fields.Many2one('freight.statement', string='Statement', required=True,
                                   ondelete='cascade', index=True)
    freight_service_id = fields.Many2one('freight.service', string='Freight Service',
                                         required=True, ondelete='restrict', index=True)
    sequence = fields.Integer(string='Sequence', default=10)
    product_id = fields.Many2one('product.product', string='Product',
                                 related='freight_service_id.service_id',
                                 store=True, readonly=True)
    name = fields.Char(string='Description', required=True)
    service_type = fields.Selection(related='freight_service_id.service_type',
                                    string='Service To', store=True, readonly=True)
    partner_id = fields.Many2one('res.partner', string='Invoice To',
                                 compute='_compute_partner', store=True)
    qty = fields.Float(string='Quantity', default=1.0, required=True)
    price_unit = fields.Monetary(string='Unit Price', currency_field='currency_id',
                                 required=True)
    currency_id = fields.Many2one('res.currency', string='Currency', required=True)
    company_currency_id = fields.Many2one('res.currency',
                                          related='statement_id.currency_id',
                                          string='Company Currency', store=True,
                                          readonly=True)
    tax_code = fields.Char(string='Tax Code', readonly=True)
    tax_name = fields.Char(string='Tax Name', readonly=True)
    tax_rate = fields.Float(string='Tax Rate (%)', readonly=True)
    tax_amount = fields.Monetary(string='Tax Amount', currency_field='currency_id')
    amount_untaxed = fields.Monetary(string='Untaxed Amount', currency_field='currency_id',
                                     compute='_compute_amounts', store=True)
    amount_total = fields.Monetary(string='Total Amount', currency_field='currency_id',
                                   compute='_compute_amounts', store=True)
    settlement_rate = fields.Float(string='Settlement Rate', digits=(12, 6), default=1.0)
    amount_untaxed_company = fields.Monetary(string='Untaxed Amount (Company)',
                                             currency_field='company_currency_id',
                                             compute='_compute_amounts', store=True)
    tax_amount_company = fields.Monetary(string='Tax Amount (Company)',
                                         currency_field='company_currency_id',
                                         compute='_compute_amounts', store=True)
    amount_total_company = fields.Monetary(string='Total Amount (Company)',
                                           currency_field='company_currency_id',
                                           compute='_compute_amounts', store=True)

    @api.depends('freight_service_id.service_type', 'freight_service_id.shipper_id',
                 'freight_service_id.consignee_id')
    def _compute_partner(self):
        for line in self:
            service = line.freight_service_id
            line.partner_id = service.shipper_id if service.service_type == 'shipper' \
                else service.consignee_id

    @api.depends('price_unit', 'qty', 'tax_amount', 'settlement_rate')
    def _compute_amounts(self):
        for line in self:
            line.amount_untaxed = line.price_unit * line.qty
            line.amount_total = line.amount_untaxed + line.tax_amount
            rate = line.settlement_rate or 1.0
            line.amount_untaxed_company = line.amount_untaxed * rate
            line.tax_amount_company = line.tax_amount * rate
            line.amount_total_company = line.amount_total * rate

    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            statement = self.env['freight.statement'].browse(vals.get('statement_id'))
            if not statement or statement.state != 'draft':
                raise ValidationError(_(
                    'Statement lines can only be created on draft statements through '
                    'the generation wizard.'))
        return super().create(vals_list)

    def write(self, vals):
        for line in self:
            if line.statement_id.state in ('voided', 'confirmed', 'draft_invoice'):
                raise ValidationError(_(
                    'Statement lines are immutable once the statement is voided, '
                    'confirmed or invoiced.'))
            allowed = {'tax_amount', 'settlement_rate'}
            if set(vals) - allowed:
                raise ValidationError(_(
                    'Statement fee amounts are snapshots. Modify the fee in '
                    'freight.shipment / freight.service and regenerate the statement.'))
        return super().write(vals)

    def unlink(self):
        raise ValidationError(_(
            'Statement lines are snapshots and cannot be removed. Void the whole '
            'statement and regenerate it from freight.service.'))
